USE p2015;

-- Tabla HISTORIAL_PRESTAMOS (Ahora una tabla regular, sin system versioning)
CREATE TABLE `HISTORIAL_PRESTAMOS`(
    `OPERACION` INT NOT NULL,
    `FECHA` DATETIME NULL,
    `IDCLIENTE` INT NULL,
    `IDACREEDOR` INT NULL,
    `TIPOOPERACION` VARCHAR(50) NULL,
    `TIPOGARANTIA` VARCHAR(50) NULL,
    `HIPOTECANTE` VARCHAR(200) NULL,
    `PADRONHIPOTECARIO` VARCHAR(200) NULL,
    `DADORENPRENDA` VARCHAR(200) NULL,
    `VEHICULOPRENDADO` VARCHAR(200) NULL,
    `CAPITALINICIAL` DOUBLE NULL,
    `MONEDA` VARCHAR(20) NULL,
    `CUOTAS` DOUBLE NULL,
    `TIPODECUOTAS` VARCHAR(100) NULL,
    `TEA` DOUBLE NULL,
    `TEM` DOUBLE NULL,
    `TMORA` DOUBLE NULL,
    `PRIMERVENCIMIENTO` VARCHAR(30) NULL,
    `LUGARDEPAGO` VARCHAR(150) NULL,
    `CARPETA` VARCHAR(100) NULL,
    `OBSERVACIONES` VARCHAR(500) NULL,
    `CAPITAL` DOUBLE NULL,
    `COMENTARIOS` TEXT NULL, -- Era varchar(7999)
    `TIPODEVENCIMIENTO` VARCHAR(100) NULL,
    `VENCIMIENTOFINAL` VARCHAR(2000) NULL,
    `SysStartTime` DATETIME(6) NOT NULL, -- Ya no GENERATED ALWAYS
    `SysEndTime` DATETIME(6) NOT NULL   -- Ya no GENERATED ALWAYS
    -- Considera añadir una clave primaria o índices a esta tabla de historial
) ENGINE=InnoDB;

-- Tabla PRESTAMO (System Versioning eliminado)
CREATE TABLE `PRESTAMO`(
    `OPERACION` INT NOT NULL AUTO_INCREMENT,
    `FECHA` DATETIME NULL,
    `IDCLIENTE` INT NULL,
    `IDACREEDOR` INT NULL,
    `TIPOOPERACION` VARCHAR(50) NULL,
    `TIPOGARANTIA` VARCHAR(50) NULL,
    `HIPOTECANTE` VARCHAR(200) NULL,
    `PADRONHIPOTECARIO` VARCHAR(200) NULL,
    `DADORENPRENDA` VARCHAR(200) NULL,
    `VEHICULOPRENDADO` VARCHAR(200) NULL,
    `CAPITALINICIAL` DOUBLE NULL,
    `MONEDA` VARCHAR(20) NULL,
    `CUOTAS` DOUBLE NULL,
    `TIPODECUOTAS` VARCHAR(100) NULL,
    `TEA` DOUBLE NULL,
    `TEM` DOUBLE NULL,
    `TMORA` DOUBLE NULL,
    `PRIMERVENCIMIENTO` VARCHAR(30) NULL,
    `LUGARDEPAGO` VARCHAR(150) NULL,
    `CARPETA` VARCHAR(100) NULL,
    `OBSERVACIONES` VARCHAR(500) NULL,
    `CAPITAL` DOUBLE NULL,
    `COMENTARIOS` TEXT NULL, -- Era varchar(7999)
    `TIPODEVENCIMIENTO` VARCHAR(100) NULL,
    `VENCIMIENTOFINAL` VARCHAR(2000) NULL,
    `SysStartTime` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), -- Simulación
    `SysEndTime` DATETIME(6) NOT NULL DEFAULT '9999-12-31 23:59:59.999999', -- Simulación
    PRIMARY KEY (`OPERACION`)
) ENGINE=InnoDB;

-- Tabla ACREEDORES
CREATE TABLE `ACREEDORES`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NOMBRES` VARCHAR(80) NULL,
    `APELLIDOS` VARCHAR(80) NULL,
    `DOCUMENTO` INT NULL,
    `DIRECCION` VARCHAR(150) NULL,
    `TELFIJO` VARCHAR(25) NULL,
    `TELCELULAR` VARCHAR(25) NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

-- Tabla AUDITORIA_PRESTAMOS
CREATE TABLE `AUDITORIA_PRESTAMOS`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `USUARIO_ID` INT NOT NULL, -- Asegúrate que esta columna exista en USUARIO o que la referencia sea correcta
    `OPERACION` INT NOT NULL, -- Referencia a PRESTAMO.OPERACION
    `MODIFICACION` DATETIME NULL,
    `ACCION` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`ID`)
    -- Considera añadir FOREIGN KEYs si es necesario, ej:
    -- FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO`(`ID`),
    -- FOREIGN KEY (`OPERACION`) REFERENCES `PRESTAMO`(`OPERACION`)
) ENGINE=InnoDB;

-- Tabla calculadora
CREATE TABLE `calculadora`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `texto` LONGTEXT NULL, -- Era varchar(max)
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;

-- Tabla CLIENTES
CREATE TABLE `CLIENTES`(
    `IDCLIENTE` INT NOT NULL AUTO_INCREMENT,
    `NOMBRES` VARCHAR(200) NULL,
    `DIRECCION` VARCHAR(200) NULL,
    `TELFIJO` VARCHAR(25) NULL,
    `TELCELULAR` VARCHAR(25) NULL,
    `EMAIL` VARCHAR(50) NULL,
    PRIMARY KEY (`IDCLIENTE`)
) ENGINE=InnoDB;

-- Tabla CUOTAS
CREATE TABLE `CUOTAS`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `IDCLIENTE` INT NULL,
    `CAPITAL` DOUBLE NULL,
    `OPERACION` INT NULL,
    `NUMERO` INT NULL,
    `MONTO` DOUBLE NULL,
    `PAGO` DOUBLE NULL,
    `VENCE` DATETIME NULL,
    `MONEDA` VARCHAR(20) NULL,
    `TIPOOPERACION` VARCHAR(100) NULL,
    `TIPODECUOTAS` VARCHAR(100) NULL,
    `ESTADO` VARCHAR(100) NULL,
    `NUMERODEPAGO` INT NULL,
    PRIMARY KEY (`ID`)
    -- Considera añadir FOREIGN KEYs
) ENGINE=InnoDB;

-- Tabla CUOTAS_BORRADAS
CREATE TABLE `CUOTAS_BORRADAS`(
    `ID` INT NULL, -- No puede ser AUTO_INCREMENT si no es PRIMARY KEY o UNIQUE
    `IDCLIENTE` INT NULL,
    `CAPITAL` FLOAT NULL, -- Era real
    `OPERACION` INT NULL,
    `NUMERO` INT NULL,
    `MONTO` INT NULL, -- ¿Seguro que es INT y no DOUBLE/FLOAT?
    `PAGO` INT NULL,  -- ¿Seguro que es INT y no DOUBLE/FLOAT?
    `VENCE` DATETIME NULL,
    `MONEDA` VARCHAR(20) NULL,
    `TIPOOPERACION` VARCHAR(100) NULL,
    `TIPODECUOTAS` VARCHAR(100) NULL,
    `ESTADO` VARCHAR(100) NULL,
    `NUMERODEPAGO` INT NULL
    -- Considera un índice o clave primaria si esta tabla se consulta mucho
) ENGINE=InnoDB;

-- Tabla CUOTAS_RESPALDO
CREATE TABLE `CUOTAS_RESPALDO`(
    `ID` INT NOT NULL AUTO_INCREMENT, -- Asumo que debería ser autoincremental y PK
    `IDCLIENTE` INT NULL,
    `CAPITAL` DOUBLE NULL,
    `OPERACION` INT NULL,
    `NUMERO` INT NULL,
    `MONTO` DOUBLE NULL,
    `PAGO` DOUBLE NULL,
    `VENCE` DATETIME NULL,
    `MONEDA` VARCHAR(20) NULL,
    `TIPOOPERACION` VARCHAR(100) NULL,
    `TIPODECUOTAS` VARCHAR(100) NULL,
    `ESTADO` VARCHAR(100) NULL,
    `NUMERODEPAGO` INT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

-- Tabla ESTADO_SITUACION
CREATE TABLE `ESTADO_SITUACION`(
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Fecha` DATE NULL,
    `CodigoOperacion` INT NULL,
    `Concepto` VARCHAR(300) NULL,
    `CodigoMovimiento` INT NULL,
    `TipoDeCuotas` VARCHAR(50) NULL,
    `CashDolares` DECIMAL(18, 0) NULL,
    `CashPesos` DECIMAL(18, 0) NULL,
    `MontoDolares` DOUBLE NULL,
    `MontoUI` DOUBLE NULL,
    PRIMARY KEY (`Id`)
) ENGINE=InnoDB;

-- Tabla HISTORIAL_ACCESOS
CREATE TABLE `HISTORIAL_ACCESOS`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `USUARIO_ID` INT NULL, -- Debe coincidir con el tipo de USUARIO.ID
    `INGRESO` DATETIME NULL,
    `SALIDA` DATETIME NULL,
    PRIMARY KEY (`ID`)
    -- FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO`(`ID`)
) ENGINE=InnoDB;

-- Tabla IMPRIMIRCUOTAS
CREATE TABLE `IMPRIMIRCUOTAS`(
    `CAPITAL` VARCHAR(150) NULL,
    `MESES` VARCHAR(150) NULL,
    `CUOTASENUI` VARCHAR(150) NULL,
    `CUOTAENPESOS` VARCHAR(150) NULL
) ENGINE=InnoDB;

-- Tabla IMPRIMIRLIQUIDACION
CREATE TABLE `IMPRIMIRLIQUIDACION`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `CONCEPTO` VARCHAR(500) NULL,
    `MONTO` DOUBLE NULL,
    `FECHAINICIO` VARCHAR(50) NULL,
    `FECHAHASTA` VARCHAR(50) NULL,
    `DIAS` VARCHAR(50) NULL,
    `MORA` DOUBLE NULL,
    `TOTAL` DOUBLE NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

-- Tabla MANUALES
CREATE TABLE `MANUALES`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NOMBRE` VARCHAR(200) NULL,
    `ARCHIVO` LONGBLOB NULL, -- Era varbinary(max)
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

-- Tabla PAGOS
CREATE TABLE `PAGOS`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NUMERO` INT NULL,
    `IDCLIENTE` INT NULL,
    `IDCUOTA` INT NULL,
    `MONTO` DOUBLE NULL,
    `FECHA` DATETIME NULL,
    `TIPOCUOTA` VARCHAR(100) NULL,
    `TIPO` VARCHAR(100) NULL,
    `OPERACION` INT NULL,
    PRIMARY KEY (`ID`)
    -- FOREIGN KEYs
) ENGINE=InnoDB;

-- Tabla PAGOS_BORRADOS
CREATE TABLE `PAGOS_BORRADOS`(
    `ID` INT NOT NULL, -- En SQL Server era PK, aquí necesitaría ser PK o UNIQUE si quieres evitar duplicados
    `NUMERO` INT NULL,
    `IDCLIENTE` INT NULL,
    `IDCUOTA` INT NULL,
    `MONTO` FLOAT NULL, -- Era real
    `FECHA` DATETIME NULL,
    `TIPOCUOTA` VARCHAR(100) NULL,
    `TIPO` VARCHAR(100) NULL,
    `OPERACION` INT NULL,
    PRIMARY KEY (`ID`) -- Asumiendo que ID sigue siendo la PK
) ENGINE=InnoDB;

-- Tabla PAGOSRESPALDO
CREATE TABLE `PAGOSRESPALDO`(
    `ID` INT NULL, -- Considera si esta tabla necesita una PK o ser AUTO_INCREMENT
    `NUMERO` INT NULL,
    `IDCLIENTE` INT NULL,
    `IDCUOTA` INT NULL,
    `MONTO` DOUBLE NULL,
    `FECHA` DATETIME NULL,
    `TIPOCUOTA` VARCHAR(100) NULL,
    `TIPO` VARCHAR(100) NULL,
    `OPERACION` INT NULL
) ENGINE=InnoDB;

-- Tabla PAGOSTOTAL
CREATE TABLE `PAGOSTOTAL`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `IDCLIENTE` INT NULL,
    `NOMBRE_DEUDOR` VARCHAR(100) NULL,
    `MONTO` DOUBLE NULL,
    `FECHA` DATETIME NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

-- Tabla PDFOPERACION
CREATE TABLE `PDFOPERACION`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `IDCLIENTE` INT NULL,
    `NOMBRE` VARCHAR(200) NULL,
    `IDOPERACION` INT NULL,
    `ARCHIVO` LONGBLOB NULL, -- Era varbinary(max)
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

-- Tabla PRESTAMO_RESPALDO
CREATE TABLE `PRESTAMO_RESPALDO`(
    `OPERACION` INT NOT NULL AUTO_INCREMENT, -- Asumo que es PK
    `FECHA` DATETIME NULL,
    `IDCLIENTE` INT NULL,
    `IDACREEDOR` INT NULL,
    `TIPOOPERACION` VARCHAR(50) NULL,
    `TIPOGARANTIA` VARCHAR(50) NULL,
    `HIPOTECANTE` VARCHAR(200) NULL,
    `PADRONHIPOTECARIO` VARCHAR(200) NULL,
    `DADORENPRENDA` VARCHAR(200) NULL,
    `VEHICULOPRENDADO` VARCHAR(200) NULL,
    `CAPITALINICIAL` DOUBLE NULL,
    `MONEDA` VARCHAR(20) NULL,
    `CUOTAS` DOUBLE NULL,
    `TIPODECUOTAS` VARCHAR(100) NULL,
    `TEA` DOUBLE NULL,
    `TEM` DOUBLE NULL,
    `TMORA` DOUBLE NULL,
    `PRIMERVENCIMIENTO` VARCHAR(30) NULL,
    `LUGARDEPAGO` VARCHAR(150) NULL,
    `CARPETA` VARCHAR(100) NULL,
    `OBSERVACIONES` VARCHAR(500) NULL,
    `CAPITAL` DOUBLE NULL,
    `COMENTARIOS` TEXT NULL, -- Era varchar(7999)
    `TIPODEVENCIMIENTO` VARCHAR(100) NULL,
    `VENCIMIENTOFINAL` VARCHAR(2000) NULL,
    PRIMARY KEY (`OPERACION`)
) ENGINE=InnoDB;

-- Tabla PRESTAMOS_BORRADOS
CREATE TABLE `PRESTAMOS_BORRADOS`(
    `OPERACION` INT NOT NULL, -- En SQL Server era PK
    `FECHA` DATETIME NULL,
    `IDCLIENTE` INT NULL,
    `IDACREEDOR` INT NULL,
    `TIPOOPERACION` VARCHAR(50) NULL,
    `TIPOGARANTIA` VARCHAR(50) NULL,
    `HIPOTECANTE` VARCHAR(200) NULL,
    `PADRONHIPOTECARIO` VARCHAR(200) NULL,
    `DADORENPRENDA` VARCHAR(200) NULL,
    `VEHICULOPRENDADO` VARCHAR(200) NULL,
    `CAPITALINICIAL` FLOAT NULL, -- Era real
    `MONEDA` VARCHAR(50) NULL,
    `CUOTAS` FLOAT NULL, -- Era real
    `TIPODECUOTAS` VARCHAR(50) NULL,
    `TEA` FLOAT NULL, -- Era real
    `TEM` FLOAT NULL, -- Era real
    `TMORA` FLOAT NULL, -- Era real
    `PRIMERVENCIMIENTO` VARCHAR(30) NULL,
    `LUGARDEPAGO` VARCHAR(150) NULL,
    `CARPETA` VARCHAR(100) NULL,
    `OBSERVACIONES` VARCHAR(500) NULL,
    `CAPITAL` FLOAT NULL, -- Era real
    `COMENTARIOS` TEXT NULL, -- Era varchar(7999)
    `TIPODEVENCIMIENTO` VARCHAR(100) NULL,
    `VENCIMIENTOFINAL` VARCHAR(2000) NULL,
    PRIMARY KEY (`OPERACION`)
) ENGINE=InnoDB;

-- Tabla SOLICITUDES
CREATE TABLE `SOLICITUDES`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NOMBRE` VARCHAR(300) NULL,
    `TELEFONO` VARCHAR(200) NULL,
    `EMAIL` VARCHAR(200) NULL,
    `MONTO` VARCHAR(200) NULL,
    `GARANTIA` TEXT NULL, -- Era varchar(max)
    `FECHA` DATETIME NULL,
    `ESTADO` VARCHAR(200) NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

-- Tabla USUARIO
CREATE TABLE `USUARIO`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `USUARIO` VARCHAR(50) NULL,
    `CONTRASEÑA` VARCHAR(50) NULL, -- ¡DEBERÍAS HASHEAR ESTO!
    `TIPO` VARCHAR(50) NULL,
    `NOMBRE` VARCHAR(150) NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UQ_USUARIO_USUARIO` (`USUARIO`) -- Añadir índice único al nombre de usuario es buena práctica
) ENGINE=InnoDB;